env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2021
  sourceType: module
rules: {
  no-console: 0,
  import/extensions: 0,
  linebreak-style: 0
}

